name: papyrus
description: Parser and Linter for papyrus language.
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  recase: ^4.0.0
  charcode: ^1.2.0

dev_dependencies:
  test: ^1.17.2
